### PR TITLE
Patch out strict requirement on protobuf version

### LINKED ISSUE #65: broken `pip check` for tensorboard affects all downstream packages
Not only does this PR break `pip check` for the tensorboard recipe, it also [breaks `pip check`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=565471&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d) for every package that depends on tensorboard, requiring them to either remove `pip check` or [pin protobuf](https://github.com/conda-forge/torchgeo-feedstock/pull/8/commits/53275cbf13f427354a5813d3be52d4895f66ac88). Is there any reason for this recipe to have a different set of dependency version requirements than the published wheel?

_Originally posted by @adamjstewart in https://github.com/conda-forge/tensorboard-feedstock/issues/64#issuecomment-1241356362_

### LINKED ISSUE #66: Remove requirements from metadata
### Comment:

@conda-forge-admin please rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

Closes #66.
Closes #65.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Thanks a lot!

**Comment by adamjstewart** [comment]
I would propose modifying:
```yaml
protobuf >=3.9.2
```
to:
```yaml
protobuf >=3.9.2,<4
```
TensorBoard definitely doesn't support protobuf 4.X since it's backwards incompatible with protobuf 3.X.

**Comment by h-vetinari** [comment]
> TensorBoard definitely doesn't support protobuf 4.X since it's backwards incompatible with protobuf 3.X.

This is actually a problem, because we have 4.21 builds live already

**Comment by adamjstewart** [comment]
See https://github.com/tensorflow/tensorboard/issues/5708. Upstream doesn't pin protobuf just for fun 😄

**Comment by adamjstewart** [comment]
protobuf 3.20 is now officially supported upstream in master: https://github.com/tensorflow/tensorboard/pull/5922

protobuf 4.21 is not supported, and will likely break: https://github.com/tensorflow/tensorboard/issues/5708

**Pull request merged**
