### PR TITLE
add py310 pls

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@xhochy any reason why it wasn't ready if that remains the case? https://github.com/ngam/tensorboard-feedstock/commit/df78b862a1d0356446f822a910e1ade23df407ff

**Comment by xhochy** [comment]
Last time I checked there were some import errors on Python 3.10 due to things being moved in the collections.abc module.

**Comment by ngam** [comment]
> Last time I checked there were some import errors on Python 3.10 due to things being moved in the collections.abc module.

How can I investigate this further? Could we add a test here?

**Comment by xhochy** [comment]
I have no idea how to add a reliable test here. You could change the python pin to exactly 3.10 and let CI run. This should show you whether it works.

**Comment by ngam** [comment]
> I have no idea how to add a reliable test here. You could change the python pin to exactly 3.10 and let CI run. This should show you whether it works.

it's passing [4d2b9c8](https://github.com/conda-forge/tensorboard-feedstock/pull/59/commits/4d2b9c880fc62f148a389bbce021b269148f10c8)

reverting, and thus ready to merge

**Comment by xhochy** [comment]
You need to bump the build no

Also feel free to add yourself as a maintainer!

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
> You need to bump the build no
> 
> Also feel free to add yourself as a maintainer!

Thanks! Let's try to get tf 2.8.0 out very soon. I believe everything is ready and we are just waiting for this and for keras to relax (so if you could you please have a look there too, that'd be super great: https://github.com/conda-forge/keras-feedstock/pull/58)

**Pull request merged**
