### PR TITLE
Upgrade to 1.15 and remove tensorflow dependency

### LINKED ISSUE #12: Trying to upgrade tensorboard to 1.10.0 is causing conda to downgrade tensorflow to 1.1.0
Issue:

Command: `~$ conda install tensorboard=1.10`

Output:
```
Solving environment: done

## Package Plan ##

  environment location: <>/anaconda3

  added / updated specs: 
    - tensorboard=1.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    tensorboard-1.10.0         |           py36_0         3.3 MB  conda-forge
    tensorflow-1.1.0           |           py36_0        25.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        28.6 MB

The following packages will be UPDATED:

    tensorboard: 1.9.0-py36_0 conda-forge --> 1.10.0-py36_0 conda-forge

The following packages will be DOWNGRADED:

    tensorflow:  1.9.0-py36_0 conda-forge --> 1.1.0-py36_0  conda-forge

Proceed ([y]/n)?
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at <>:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0  
absl-py                   0.3.0                      py_0    conda-forge
alabaster                 0.7.11                     py_3    conda-forge
anaconda                  custom           py36hbbc8b67_0  
anaconda-client           1.6.14                     py_0    conda-forge
anaconda-navigator        1.8.7                    py36_0  
anaconda-project          0.8.2                      py_1    conda-forge
apiai                     1.2.3                     <pip>
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                     py_1    conda-forge
astor                     0.7.1                      py_0    conda-forge
astroid                   1.6.5                    py36_0    conda-forge
astropy                   3.0.3                    py36_1    conda-forge
atomicwrites              1.1.5                    py36_0    conda-forge
attrs                     18.1.0                     py_1    conda-forge
automat                   0.7.0                    py36_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports.weakref         1.0.post1                py36_0    conda-forge
beautifulsoup4            4.6.1                    py36_0    conda-forge
bitarray                  0.8.3            py36h470a237_0    conda-forge
bkcharts                  0.2                      py36_0    conda-forge
blas                      1.0                         mkl  
blaze                     0.11.3                   py36_0    conda-forge
bleach                    1.5.0                    py36_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.14.4               hfc679d8_0    conda-forge
bokeh                     0.13.0                   py36_0    conda-forge
boto                      2.49.0                   py36_0  
boto3                     1.7.66                     py_0    conda-forge
botocore                  1.10.67                    py_0    conda-forge
bottleneck                1.2.1            py36h7eb728f_1    conda-forge
bz2file                   0.98                     py36_1  
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.12              he56eebe_3    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                    py36_2    conda-forge
click                     6.7                        py_1    conda-forge
cloudpickle               0.5.3                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.3.9                      py_1    conda-forge
conda                     4.5.9                    py36_0    conda-forge
conda-build               3.11.0                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-verify              3.0.1                    py36_0    conda-forge
constantly                15.1.0                     py_0    conda-forge
contextlib2               0.5.5                      py_2    conda-forge
coverage                  4.5.1            py36h470a237_1    conda-forge
cryptography              2.3              py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3                      py36_0    conda-forge
cudatoolkit               9.0                  h13b8566_0  
cudnn                     7.1.2                 cuda9.0_0  
cupti                     9.0.176                       0  
curl                      7.61.0               h93b3f91_1    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.28.4           py36hfc679d8_1    conda-forge
cytoolz                   0.9.0.1          py36h470a237_0    conda-forge
dask                      0.18.2                     py_0    conda-forge
dask-core                 0.18.2                     py_0    conda-forge
datashape                 0.5.4                    py36_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
distributed               1.22.0                   py36_0    conda-forge
django                    2.0.7                    py36_0    conda-forge
dnspython                 1.15.0                    <pip>
docutils                  0.14                     py36_0    conda-forge
ecdsa                     0.13                      <pip>
Electron-Cash             3.0                       <pip>
entrypoints               0.2.3                    py36_1    conda-forge
et_xmlfile                1.0.1                    py36_0    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
fastcache                 1.0.2            py36h470a237_1    conda-forge
filelock                  3.0.4                      py_1    conda-forge
flask                     1.0.2                      py_1    conda-forge
flask-cors                3.0.6                      py_0    conda-forge
fontconfig                2.13.0               h0c61d53_4    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
fribidi                   1.0.4                h14c3975_0  
gast                      0.2.0                      py_0    conda-forge
gensim                    3.5.0                    py36_0    conda-forge
get_terminal_size         1.0.0                haa9412d_0  
gettext                   0.19.8.1                      0    conda-forge
gevent                    1.3a1                    py36_0    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
glob2                     0.6                        py_0    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gmpy2                     2.0.8                    py36_1    conda-forge
graphite2                 1.3.11               hfc679d8_0    conda-forge
greenlet                  0.4.13                   py36_0    conda-forge
grpcio                    1.12.1           py36hdbcaa40_0  
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h61a6719_0    conda-forge
h5py                      2.8.0            py36hb794570_1    conda-forge
harfbuzz                  1.8.4                h2bb21d5_0    conda-forge
hdf5                      1.10.2               hc401514_1    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
html5lib                  0.9999999                py36_0    conda-forge
hyperlink                 17.3.1                     py_0    conda-forge
hypothesis                3.66.14          py36h24bf2e0_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py36_2    conda-forge
imageio                   2.3.0                      py_1    conda-forge
imagesize                 1.0.0                      py_1    conda-forge
incremental               17.5.0                     py_0    conda-forge
intel-openmp              2018.0.3                      0  
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.5.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.3.1                      py_0    conda-forge
isort                     4.3.4                    py36_0    conda-forge
itsdangerous              0.24                       py_2    conda-forge
jbig                      2.1                           0    conda-forge
jdcal                     1.4                        py_1    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jeepney                   0.3.1                      py_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
joblib                    0.11                      <pip>
jpeg                      9c                   h470a237_0    conda-forge
jsonrpclib-pelix          0.3.1                     <pip>
jsonschema                2.6.0                    py36_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.33.4                   py36_0    conda-forge
jupyterlab_launcher       0.11.2                     py_0    conda-forge
keyring                   13.2.1                   py36_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
krb5                      1.14.6                        0    conda-forge
lazy-object-proxy         1.3.1            py36h470a237_0    conda-forge
libcurl                   7.61.0               h1ad7b7a_0  
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libiconv                  1.15                 h470a237_1    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.34               ha92aebf_1    conda-forge
libprotobuf               3.5.2                hd28b015_1    conda-forge
libsodium                 1.0.16                        0    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he6b73bb_1    conda-forge
libtool                   2.4.6                h470a237_1    conda-forge
libuuid                   1.0.3                         1    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
libxslt                   1.1.32               h88dbc4e_1    conda-forge
llvmlite                  0.23.0                   py36_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.2.3            py36hc9114bc_0    conda-forge
lzo                       2.10                          0    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.3            py36h470a237_2    conda-forge
mkl                       2018.0.3                      1  
mkl-service               1.1.2            py36h651fb7a_4  
mkl_fft                   1.0.5                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
mock                      2.0.0                    py36_0    conda-forge
more-itertools            4.2.0                    py36_1    conda-forge
mpc                       1.1.0                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
msgpack-python            0.5.6            py36h2d50403_2    conda-forge
multipledispatch          0.5.0                    py36_0    conda-forge
navigator-updater         0.2.1                    py36_0  
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
networkx                  2.1                        py_1    conda-forge
nltk                      3.2.5                      py_0    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.6.0                    py36_0    conda-forge
numba                     0.38.1                   py36_0    conda-forge
numexpr                   2.6.5                    py36_0    conda-forge
numpy                     1.15.0           py36h1b885b7_0  
numpy-base                1.15.0           py36h3dfced4_0  
numpydoc                  0.8.0                      py_1    conda-forge
oauthlib                  2.1.0                      py_0    conda-forge
odo                       0.5.1                      py_1    conda-forge
olefile                   0.45.1                     py_1    conda-forge
openblas                  0.2.20                        8    conda-forge
openblas-devel            0.2.20                        7  
openpyxl                  2.5.4                      py_1    conda-forge
openssl                   1.0.2o               h470a237_1    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.3           py36hf8a1672_1    conda-forge
pandoc                    2.2.2                         1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14              h9105a7a_2    conda-forge
parfit                    0.191                     <pip>
parso                     0.3.1                      py_0    conda-forge
partd                     0.3.8                      py_1    conda-forge
patchelf                  0.9                           2    conda-forge
path.py                   11.0.1                     py_0    conda-forge
pathlib2                  2.3.2                    py36_0    conda-forge
patsy                     0.5.0                      py_1    conda-forge
pbr                       4.2.0                      py_0    conda-forge
pcre                      8.41                 h470a237_2    conda-forge
PDPbox                    0.1                       <pip>
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    5.2.0                    py36_0    conda-forge
pip                       18.0                     py36_0    conda-forge
pixman                    0.34.0                        2    conda-forge
pkginfo                   1.4.2                      py_1    conda-forge
pluggy                    0.7.1                      py_0    conda-forge
ply                       3.11                       py_1    conda-forge
pprintpp                  0.3.0                    py36_0    conda-forge
prometheus_client         0.3.0                      py_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
protobuf                  3.5.2            py36hd28b015_0    conda-forge
psutil                    5.4.6                    py36_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
py                        1.5.4                      py_0    conda-forge
pyasn1                    0.4.4                      py_0    conda-forge
pyasn1-modules            0.2.1                      py_0    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycosat                   0.6.3            py36h470a237_1    conda-forge
pycparser                 2.18                       py_1    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pycurl                    7.43.0.2         py36hb7f436b_0  
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyhamcrest                1.9.0                      py_2    conda-forge
pyjwt                     1.6.4                      py_0    conda-forge
pylint                    1.9.2                    py36_0    conda-forge
pympler                   0.5                      py36_0    conda-forge
pyodbc                    4.0.23           py36hfc679d8_1    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyqt                      5.6.0            py36h8210e8a_6    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
pytables                  3.4.4            py36h4f72b40_1    conda-forge
pytest                    3.7.0                    py36_0    conda-forge
pytest-arraydiff          0.2                        py_0    conda-forge
pytest-astropy            0.4.0                      py_0    conda-forge
pytest-doctestplus        0.1.3                      py_0    conda-forge
pytest-openfiles          0.3.0                      py_0    conda-forge
pytest-remotedata         0.3.0                      py_0    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-crfsuite           0.9.5            py36h470a237_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pywavelets                0.5.2            py36h7eb728f_2    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     17.1.0           py36hae99301_0    conda-forge
qrcode                    5.3                       <pip>
qt                        5.6.2                h50c60fd_8    conda-forge
qtawesome                 0.4.4              pyh8a2030e_1    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.4.2              pyh8a2030e_1    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.19.1                   py36_1    conda-forge
requests-oauthlib         1.0.0                      py_1    conda-forge
rope                      0.10.7                     py_1    conda-forge
ruamel_yaml               0.15.46          py36h470a237_0    conda-forge
s3transfer                0.1.13                   py36_0    conda-forge
scikit-image              0.14.0           py36hfc679d8_1    conda-forge
scikit-learn              0.19.1           py36hedc7406_0  
scipy                     1.1.0            py36hc49cb51_0  
seaborn                   0.9.0                      py_0    conda-forge
secretstorage             3.0.1                    py36_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setuptools                40.0.0                   py36_1    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3                  py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sklearn                   0.0                       <pip>
smart_open                1.6.0                      py_1    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcollections         1.0.1                      py_1    conda-forge
sortedcontainers          2.0.4                      py_1    conda-forge
sphinx                    1.7.5                    py36_0    conda-forge
sphinxcontrib             1.0                      py36_1  
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
spyder                    3.2.8                    py36_0    conda-forge
spyder-kernels            1.0.1                      py_1    conda-forge
sqlalchemy                1.2.10           py36h470a237_1    conda-forge
sqlite                    3.24.0               h2f33b56_0    conda-forge
statsmodels               0.9.0                    py36_0    conda-forge
sympy                     1.2                      py36_0    conda-forge
tblib                     1.3.2                      py_1    conda-forge
tensorboard               1.9.0                    py36_0    conda-forge
tensorflow                1.9.0                    py36_0    conda-forge
tensorflow-base           1.9.0           gpu_py36h6ecc378_0  
tensorflow-tensorboard    1.5.1            py36hf484d3e_1  
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.6.8                         0    conda-forge
toolz                     0.9.0                      py_0    conda-forge
tornado                   5.1                      py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
treeinterpreter           0.2.1                     <pip>
twisted                   17.5.0                   py36_0  
twython                   3.7.0                      py_0    conda-forge
typing                    3.6.4                    py36_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unixodbc                  2.3.5                h09ba92c_1    conda-forge
urllib3                   1.23                     py36_0    conda-forge
waterfallcharts           3.8                       <pip>
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5                      py36_0    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
widgetsnbextension        3.3.1                    py36_1    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xlrd                      1.1.0                      py_2    conda-forge
xlsxwriter                1.0.5                      py_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.2                h470a237_5    conda-forge
xorg-libx11               1.6.5                h470a237_2    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_0    conda-forge
yaml                      0.1.7                         0    conda-forge
zeromq                    4.2.5                hfc679d8_5    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
zope                      1.0                      py36_0  
zope.interface            4.5.0            py36h470a237_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

active environment : None
       user config file : <>/.condarc
 populated config files : <>/.condarc
          conda version : 4.5.9
    conda-build version : 3.11.0
         python version : 3.6.6.final.0
       base environment : <>  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : <>/pkgs
                          <>/.conda/pkgs
       envs directories : <>/anaconda3/envs
                          <>/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.9 requests/2.19.1 CPython/3.6.6 Linux/4.15.0-29-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by mdraw**
Closes #12

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Since versions 1.14 and 1.15, most tensorboard features work without tensorflow.
This PR upgrades the version to 1.15, removes the requirement of tensorflow, adds absl-py and grpcio dependencies and enables a basic CLI test.

### CODE REVIEW

**Comment by mdraw** [comment]
@conda-forge-admin, please rerender

**Comment by mdraw** [comment]
@conda-forge/tensorboard, is this ready to be merged? 2.0 is already out, but I think it would make sense to merge this PR first and rebase the 2.0 PR, because 1.15 brings a few important features and 2.0 has some major breaking changes.

**Comment by mdraw** [comment]
ping @conda-forge/tensorboard

**Comment by ostrokach** [comment]
@conda-forge/tensorboard, @mdraw Is anything holding back this PR?

**Comment by mdraw** [comment]
@conda-forge-admin, please rerender

**Comment by mdraw** [comment]
@conda-forge-admin, please restart ci

**Comment by mdraw** [comment]
@conda-forge-admin, please restart ci

**Comment by mdraw** [comment]
I think this PR is ready to be merged now. @ocefpaf, you have recently merged a PR in this feedstock. Could you please land this PR here or do you know who I can ask about this? None of the tensorboard-feedstock maintainers have been active here in the last few months.

**Comment by ocefpaf** [comment]
> @ocefpaf, you have recently merged a PR in this feedstock. Could you please land this PR here or do you know who I can ask about this?

I was only handling the py38 migration. Let's give @dougalsutherland and the @conda-forge/tensorboard team to take a look before "force merging" this one.

**Comment by mdraw** [comment]
@ocefpaf I don't think that pinging the team again would help. Should we ask someone in the admin team?

**Comment by mdraw** [comment]
Thanks for the merge, @ocefpaf :+1:

**Pull request merged**
