### PR TITLE
Fixes crashing of tensorboard when starting from the CLI

### PR DESCRIPTION
**Pull request by gilbertfrancois**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gilbertfrancois** [comment]
The entry point for starting Tensorboard from the command line used to be in the Tensorflow package. For some esoteric reason, it still is (and needs to be there for now) but now it is also in the Tensorboard package where is should be. This is in line with the original `setup.py` files.

**Comment by gilbertfrancois** [comment]
Thank you @sdvillal. It has already this test and comment (not added by me). What additional test do you suggest that can be done without having to import tensorflow?

```
test:
  imports:
    - tensorboard
  # N.B. CLI tests are in the tensorflow package recipe (to avoid having an explicit circular dependency)
  # To be super-strict, we should run the original tests with bazel against the newly created package

```

**Comment by sdvillal** [comment]
At least for linux and mac it should be something like:
```yaml
commands:
    - tensorboard --help | grep USAGE
```

But bringing back old memories, I fear this test might fail in this package with ImportError, as tensorboard actually requires tensorflow, and tensorflow cannot be released without tensorboard. So what I actually suggest is to, instead, merge this and add these tests to the tensorflow PR https://github.com/conda-forge/tensorflow-feedstock/pull/54, where you have already fixed the entrypoint too (happy to see that TF and TB wheels now have the same definition).

See #1 and https://github.com/conda-forge/tensorflow-feedstock/pull/47 (which we should close as soon as these tests pass).

**Comment by sdvillal** [comment]
I'm actually merging this now.

**Pull request merged**
