### PR TITLE
Update tensorboard to 1.5.1

### PR DESCRIPTION
**Pull request by dhirschfeld**

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Closing & reopening to restart the CI...

**Comment by dhirschfeld** [comment]
The failed appveyor builds fail with `The batch file cannot be found.`
Unfortunately I'm not sure what this means / why they're failing :|
```
set PYTHONUNBUFFERED=1
conda config --set show_channel_urls true
conda config --remove channels defaults
conda config --add channels defaults
conda config --add channels conda-forge
conda install -n root --quiet --yes conda-forge-build-setup
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\Miniconda36-x64
  added / updated specs: 
    - conda-forge-build-setup
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    conda-4.3.34               |           py36_0         540 KB  conda-forge
    yaml-0.1.7                 |           vc14_0         103 KB  conda-forge
    certifi-2018.1.18          |           py36_0         144 KB  conda-forge
    ca-certificates-2018.1.18  |                0         178 KB  conda-forge
    conda-forge-build-setup-4.4.19|                0           9 KB  conda-forge
    openssl-1.0.2n             |           vc14_0         5.4 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         6.3 MB
The following NEW packages will be INSTALLED:
    conda-forge-build-setup: 4.4.19-0                 conda-forge
The following packages will be UPDATED:
    ca-certificates:         2017.08.26-h94faf87_0    defaults    --> 2018.1.18-0      conda-forge
    certifi:                 2017.11.5-py36hb8ac631_0 defaults    --> 2018.1.18-py36_0 conda-forge
    openssl:                 1.0.2n-h74b6da3_0        defaults    --> 1.0.2n-vc14_0    conda-forge [vc14]
The following packages will be DOWNGRADED:
    conda:                   4.4.10-py36_0            defaults    --> 4.3.34-py36_0    conda-forge
    yaml:                    0.1.7-hc54c509_2         defaults    --> 0.1.7-vc14_0     conda-forge [vc14]
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
The batch file cannot be found.
Command exited with code 1
```

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by jjhelmus** [comment]
> The failed appveyor builds fail with The batch file cannot be found.

Re-rendering seems to have fixed it. merging.

**Pull request merged**
