### PR TITLE
add build for v2.2.0

### PR DESCRIPTION
**Pull request by Borda**
Adding build for v2.2.0 needed for PL 0.9, see https://github.com/conda-forge/pytorch-lightning-feedstock/pull/9

**Checklist**
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

According to the https://github.com/conda-forge/pytorch-lightning-feedstock/pull/9#issuecomment-679352491 this PR shall be merged to a spec branch than master, so pls create a new branch and change the target of this PR :]

### CODE REVIEW

**Comment by CJ-Wright** [comment]
I think you need to merge with master, since you have conflicts. Don't worry about the branch until it is ready to go in.

**Comment by Borda** [comment]
@CJ-Wright seem that the build is fine now 🐰

**Comment by CJ-Wright** [comment]
@conda-forge/tensorboard please review. It would be great if this could go on an independent branch (rather than master) since that will cause a bunch of confusion.
@conda-forge/core for vis (and maybe we need to write a walk-through of how to submit older versions?)

**Comment by Borda** [comment]
could we have just simply branch named `v2.2.0` to keep it obvious... :]

**Comment by jschueller** [comment]
moved to branch 2.2

**Comment by Borda** [comment]
@jschueller  shall it be merged?

**Comment by beckermr** [comment]
This does not need to be merged since it was pushed to a branch.

It will be the package build time plus an hour before it appears.

**Pull request closed without merging**
